version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kirastream-backend
volumes:
  postgres_data:
networks:
  kirastream-backend:
